In [0]:
import numpy as np  
 

In [0]:
X=np.array([[0,1,1,0],[1,1,0,1],[0,1,0,1]])

In [0]:
y=np.array([[1],[0],[1]])

In [0]:
#Sigmoid Function
def sigmoid (z):
  return 1/(1 + np.exp(-z))

In [0]:
#Derivative of Sigmoid Function
def derivatives_sigmoid(z):
  return z * (1 - z)

In [0]:
epoch=100 #Setting training iterations
learn_rate=0.1 #Setting learning rate
input_neurons = X.shape[1] #number of features in data set
hidden_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [0]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wout=np.random.uniform(size=(hidden_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [31]:
for i in range(epoch):

  #Forward Propogation
  hidden_layer_input1=np.dot(X,wh)
  hidden_layer_input=hidden_layer_input1 + bh
  hiddenlayer_activations = sigmoid(hidden_layer_input)
  output_layer_input1=np.dot(hiddenlayer_activations,wout)
  output_layer_input= output_layer_input1+ bout
  output = sigmoid(output_layer_input)

#Backpropagation
  E = y-output
  slope_output_layer = derivatives_sigmoid(output)
  slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
  d_output = E * slope_output_layer
  Error_at_hidden_layer = d_output.dot(wout.T)
  d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
  wout += hiddenlayer_activations.T.dot(d_output) *lr
  bout += np.sum(d_output, axis=0,keepdims=True) *lr
  wh += X.T.dot(d_hiddenlayer) *lr
  bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

  print(output)

[[0.92340387]
 [0.94316428]
 [0.93377326]]
[[0.92249554]
 [0.94238989]
 [0.93293122]]
[[0.92156903]
 [0.94159846]
 [0.93207156]]
[[0.9206239 ]
 [0.94078953]
 [0.93119383]]
[[0.91965971]
 [0.93996264]
 [0.93029755]]
[[0.91867597]
 [0.93911729]
 [0.92938227]]
[[0.91767221]
 [0.938253  ]
 [0.92844748]]
[[0.91664795]
 [0.93736924]
 [0.92749269]]
[[0.91560269]
 [0.93646549]
 [0.9265174 ]]
[[0.91453592]
 [0.93554123]
 [0.92552109]]
[[0.91344713]
 [0.9345959 ]
 [0.92450321]]
[[0.91233578]
 [0.93362893]
 [0.92346323]]
[[0.91120134]
 [0.93263975]
 [0.92240059]]
[[0.91004326]
 [0.93162777]
 [0.92131473]]
[[0.90886099]
 [0.93059239]
 [0.92020507]]
[[0.90765395]
 [0.92953299]
 [0.91907102]]
[[0.90642158]
 [0.92844895]
 [0.91791198]]
[[0.9051633 ]
 [0.92733963]
 [0.91672735]]
[[0.9038785 ]
 [0.92620436]
 [0.9155165 ]]
[[0.90256661]
 [0.9250425 ]
 [0.91427881]]
[[0.901227  ]
 [0.92385336]
 [0.91301365]]
[[0.89985909]
 [0.92263626]
 [0.91172037]]
[[0.89846225]
 [0.9213905 ]
 [0.91039832]]
[[0.8970358